snowflake:
  account: lib13297.us-east-1
  database: FYI_BUDGET_TRACKER
  schema: ['DEV', 'TEST', 'UAT', 'PROD']
  warehouse: FYI_COMPUTE_WH
  insecure_mode: True
  use_openssl_only: False
cookie:
  expiry_hours: 0
  expiry_minutes: 30